CREATE DATABASE IF NOT EXISTS petshop;
USE petshop;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  email VARCHAR(80) NOT NULL UNIQUE,
  telefone VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS animais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(60) NOT NULL,
  especie VARCHAR(30) NOT NULL,
  raca VARCHAR(60),
  idade INT,
  cliente_id INT NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE TABLE IF NOT EXISTS agendamentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  animal_id INT NOT NULL,
  servico ENUM('BANHO','TOSA','CONSULTA') NOT NULL,
  data DATE NOT NULL,
  horario TIME NOT NULL,
  status ENUM('ABERTO','CONFIRMADO','CONCLUIDO','CANCELADO') NOT NULL DEFAULT 'ABERTO',
  FOREIGN KEY (animal_id) REFERENCES animais(id)
);
